name:
  php-error-handling-test-project

services:

  test-app:
    build:
      context: .
      target: test-app
    volumes:
      - php-error-handling-test-app-logs:/var/log/test-app



  fluent-bit:
    build:
      context: .
      target: fluent-bit
    environment:
      OPENSEARCH_HOST: ${OPENSEARCH_HOST}
      OPENSEARCH_PORT: ${OPENSEARCH_PORT}
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD}
    volumes:
      - php-error-handling-test-app-logs:/var/log/test-app



volumes:
  php-error-handling-test-app-logs:
